# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest 
 steps:
- task: SSH@0
  displayName: 'Run shell commands on remote machine'
  inputs:
    sshEndpoint: 'ssh-service-connection'
    commands: 'cd C:\IRI\darkshield-api-demos-master\darkshield-api-demos-master\mongo && python main.py && exit'
