version: 0.2

env:
  parameter-store:
    IP_ADDRESS: "/IP/ADDRESS"
    SSH_PRIVATE_KEY: "/PRIVATE/KEY"
    SSH_COMMAND: "/SSH/COMMAND"
    

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install unit.js
      - apt-get update -qq
      - 'which ssh-agent || ( apt-get install -qq openssh-client )'
      - eval $(ssh-agent -s)
      - ssh-add < echo "$SSH_PRIVATE_KEY" | tr -d '\r'
      - mkdir -p ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - ssh -tt $IP_ADDRESS $SSH_COMMAND
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo "$IP_ADDRESS"
  post_build:
    commands:
      - echo Build completed on `date`
