version: 0.2

env:
  parameter-store:
    IP_ADDRESS: "/IP/ADDRESS"
    SSH_PRIVATE_KEY: "/PRIVATE/KEY"
    SSH_COMMAND: "/SSH/COMMAND"
    

phases:
  install:
    commands:
      - mkdir -p ~/.ssh && chmod 0700 ~/.ssh
      - echo -n "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 0400 ~/.ssh/id_rsa
      - md5sum ~/.ssh/id_rsa
  pre_build:
    commands:
      - 'which ssh-agent || ( apt-get install -qq openssh-client )'
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_rsa
      - ssh -o StrictHostKeyChecking=no
      - ssh -tt $IP_ADDRESS $SSH_COMMAND
  build:
    commands:
      - echo "$IP_ADDRESS"
