version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install unit.js
      - apt-get update -qq
      - 'which ssh-agent || ( apt-get install -qq openssh-client )'
      - eval $(ssh-agent -s)
      - mkdir -p ~/.ssh
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo #{codepipeline.PipelineExecutionId}
  post_build:
    commands:
      - echo Build completed on `date`
