version: 0.2

env:
  parameter-store:
    IP_ADDRESS: "/IP/ADDRESS"
    SSH_PRIVATE_KEY: "/PRIVATE/KEY"
    SSH_COMMAND: "/SSH/COMMAND"
    

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - mkdir -p ~/.ssh && chmod 0700 ~/.ssh
      - echo -n "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 0400 ~/.ssh/id_rsa
      - md5sum ~/.ssh/id_rsa
  pre_build:
    commands:
      - eval $(ssh-agent)
      - ssh-add ~/.ssh/id_rsa
      - echo $SSH_COMMAND
      - ssh -o StrictHostKeyChecking=no
      - ssh -tt $IP_ADDRESS $SSH_COMMAND
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo "$IP_ADDRESS"
  post_build:
    commands:
      - echo Build completed on `date`
